reviews:
  auto_review:
    ignore_usernames:
      - "dependabot[bot]"
      - "github-actions[bot]"
    labels:
      - "!automerge"
      - "!dependencies"
    path_filters: |
      !.github/workflows/**
