from __future__ import annotations

from typing import Final

import polars as pl

from vertex_forager.constants import DEFAULT_TIME_ZONE
from vertex_forager.core.quality import NoDuplicateRows, NoFutureDates, NoNegativePrices
from vertex_forager.schema.config import DatasetSpec, TableSchema

SHARADAR_SEP: Final[TableSchema] = TableSchema(
    table="sharadar_price",
    schema={
        "provider": pl.String,
        "ticker": pl.String,
        "date": pl.Date,
        "open": pl.Float64,
        "high": pl.Float64,
        "low": pl.Float64,
        "close": pl.Float64,
        "volume": pl.Int64,
        "closeadj": pl.Float64,
        "closeunadj": pl.Float64,
        "lastupdated": pl.Date,
        "fetched_at": pl.Datetime(time_zone=DEFAULT_TIME_ZONE),
    },
    unique_key=("provider", "ticker", "date"),
    analysis_date_col="date",
    quality_rules=(
        NoFutureDates(["date"]),
        NoNegativePrices(["open", "high", "low", "close", "closeadj", "closeunadj"]),
        NoDuplicateRows(["ticker", "date"]),
    ),
)


SHARADAR_TICKERS: Final[TableSchema] = TableSchema(
    table="sharadar_tickers",
    schema={
        "provider": pl.String,
        "table": pl.String,
        "permaticker": pl.String,
        "ticker": pl.String,
        "name": pl.String,
        "exchange": pl.String,
        "isdelisted": pl.String,
        "category": pl.String,
        "cusips": pl.String,
        "siccode": pl.String,
        "sicsector": pl.String,
        "sicindustry": pl.String,
        "famasector": pl.String,
        "famaindustry": pl.String,
        "sector": pl.String,
        "industry": pl.String,
        "scalemarketcap": pl.String,
        "scalerevenue": pl.String,
        "relatedtickers": pl.String,
        "currency": pl.String,
        "location": pl.String,
        "companysite": pl.String,
        "secfilings": pl.String,
        "lastupdated": pl.Date,
        "firstadded": pl.Date,
        "firstpricedate": pl.Date,
        "lastpricedate": pl.Date,
        "firstquarter": pl.Date,
        "lastquarter": pl.Date,
        "fetched_at": pl.Datetime(time_zone=DEFAULT_TIME_ZONE),
    },
    unique_key=("provider", "table", "ticker"),
    analysis_date_col=None,
    quality_rules=(
        NoFutureDates(["lastupdated"]),
        NoDuplicateRows(["table", "ticker"]),
    ),
)


SHARADAR_SF1: Final[TableSchema] = TableSchema(
    table="sharadar_fundamental",
    schema={
        "provider": pl.String,
        "ticker": pl.String,
        "dimension": pl.String,
        "calendardate": pl.Date,
        "datekey": pl.Date,
        "reportperiod": pl.Date,
        "fiscalperiod": pl.String,
        "lastupdated": pl.Date,
        "accoci": pl.Int64,
        "assets": pl.Int64,
        "assetsavg": pl.Int64,
        "assetsc": pl.Int64,
        "assetsnc": pl.Int64,
        "assetturnover": pl.Float64,
        "bvps": pl.Float64,
        "capex": pl.Int64,
        "cashneq": pl.Int64,
        "cashnequsd": pl.Int64,
        "cor": pl.Int64,
        "consolinc": pl.Int64,
        "currentratio": pl.Float64,
        "de": pl.Float64,
        "debt": pl.Int64,
        "debtc": pl.Int64,
        "debtnc": pl.Int64,
        "debtusd": pl.Int64,
        "deferredrev": pl.Int64,
        "depamor": pl.Int64,
        "deposits": pl.Int64,
        "divyield": pl.Float64,
        "dps": pl.Float64,
        "ebit": pl.Int64,
        "ebitda": pl.Int64,
        "ebitdamargin": pl.Float64,
        "ebitdausd": pl.Int64,
        "ebitusd": pl.Int64,
        "ebt": pl.Int64,
        "equity": pl.Int64,
        "equityavg": pl.Int64,
        "equityusd": pl.Int64,
        "eps": pl.Float64,
        "epsdil": pl.Float64,
        "epsusd": pl.Float64,
        "ev": pl.Float64,
        "evebit": pl.Float64,
        "evebitda": pl.Float64,
        "fcf": pl.Int64,
        "fcfps": pl.Float64,
        "fxusd": pl.Float64,
        "gp": pl.Int64,
        "grossmargin": pl.Float64,
        "intangibles": pl.Int64,
        "intexp": pl.Int64,
        "inventory": pl.Int64,
        "invcap": pl.Int64,
        "invcapavg": pl.Int64,
        "investments": pl.Int64,
        "investmentsc": pl.Int64,
        "investmentsnc": pl.Int64,
        "liabilities": pl.Int64,
        "liabilitiesc": pl.Int64,
        "liabilitiesnc": pl.Int64,
        "marketcap": pl.Float64,
        "ncf": pl.Int64,
        "ncfbus": pl.Int64,
        "ncfcommon": pl.Int64,
        "ncfdebt": pl.Int64,
        "ncfdiv": pl.Int64,
        "ncff": pl.Int64,
        "ncfi": pl.Int64,
        "ncfinv": pl.Int64,
        "ncfo": pl.Int64,
        "ncfx": pl.Int64,
        "netinc": pl.Int64,
        "netinccmn": pl.Int64,
        "netinccmnusd": pl.Int64,
        "netincdis": pl.Int64,
        "netincnci": pl.Int64,
        "netmargin": pl.Float64,
        "opex": pl.Int64,
        "opinc": pl.Int64,
        "payables": pl.Int64,
        "payoutratio": pl.Float64,
        "pb": pl.Float64,
        "pe": pl.Float64,
        "pe1": pl.Float64,
        "ppnenet": pl.Int64,
        "prefdivis": pl.Int64,
        "price": pl.Float64,
        "ps": pl.Float64,
        "ps1": pl.Float64,
        "receivables": pl.Int64,
        "retearn": pl.Int64,
        "revenue": pl.Int64,
        "revenueusd": pl.Int64,
        "rnd": pl.Int64,
        "roa": pl.Float64,
        "roe": pl.Float64,
        "roic": pl.Float64,
        "ros": pl.Float64,
        "sbcomp": pl.Int64,
        "sgna": pl.Int64,
        "sharefactor": pl.Float64,
        "sharesbas": pl.Int64,
        "shareswa": pl.Int64,
        "shareswadil": pl.Int64,
        "sps": pl.Float64,
        "tangibles": pl.Int64,
        "taxassets": pl.Int64,
        "taxexp": pl.Int64,
        "taxliabilities": pl.Int64,
        "tbvps": pl.Float64,
        "workingcapital": pl.Int64,
        "fetched_at": pl.Datetime(time_zone=DEFAULT_TIME_ZONE),
    },
    unique_key=("provider", "ticker", "dimension", "calendardate", "reportperiod"),
    analysis_date_col="datekey",
    quality_rules=(
        NoFutureDates(["calendardate", "datekey", "reportperiod"]),
        NoDuplicateRows(["ticker", "dimension", "calendardate", "reportperiod"]),
    ),
)


SHARADAR_SF2: Final[TableSchema] = TableSchema(
    table="sharadar_insider",
    schema={
        "provider": pl.String,
        "ticker": pl.String,
        "filingdate": pl.Date,
        "formtype": pl.String,
        "issuername": pl.String,
        "ownername": pl.String,
        "officertitle": pl.String,
        "isdirector": pl.String,
        "isofficer": pl.String,
        "istenpercentowner": pl.String,
        "transactiondate": pl.Date,
        "securityadcode": pl.String,
        "transactioncode": pl.String,
        "transactionshares": pl.Int64,
        "transactionpricepershare": pl.Float64,
        "transactionvalue": pl.Float64,
        "sharesownedbeforetransaction": pl.Int64,
        "sharesownedfollowingtransaction": pl.Int64,
        "directorindirect": pl.String,
        "natureofownership": pl.String,
        "dateexercisable": pl.Date,
        "priceexercisable": pl.Float64,
        "expirationdate": pl.Date,
        "rownum": pl.Int64,
        "securitytitle": pl.String,
        "fetched_at": pl.Datetime(time_zone=DEFAULT_TIME_ZONE),
    },
    unique_key=("provider", "ticker", "filingdate", "rownum"),
    analysis_date_col="filingdate",
    quality_rules=(
        NoFutureDates(["filingdate"]),
        NoDuplicateRows(["ticker", "filingdate", "rownum"]),
    ),
)


SHARADAR_SF3: Final[TableSchema] = TableSchema(
    table="sharadar_institutional",
    schema={
        "provider": pl.String,
        "ticker": pl.String,
        "calendardate": pl.Date,
        "investorname": pl.String,
        "securitytype": pl.String,
        "units": pl.Int64,
        "price": pl.Float64,
        "value": pl.Float64,
        "fetched_at": pl.Datetime(time_zone=DEFAULT_TIME_ZONE),
    },
    unique_key=("provider", "ticker", "calendardate", "investorname", "securitytype"),
    analysis_date_col="calendardate",
    quality_rules=(
        NoFutureDates(["calendardate"]),
        NoDuplicateRows(["ticker", "calendardate", "investorname", "securitytype"]),
    ),
)


SHARADAR_ACTIONS: Final[TableSchema] = TableSchema(
    table="sharadar_actions",
    schema={
        "provider": pl.String,
        "date": pl.Date,
        "action": pl.String,
        "ticker": pl.String,
        "name": pl.String,
        "value": pl.Float64,
        "contraticker": pl.String,
        "contraname": pl.String,
        "fetched_at": pl.Datetime(time_zone=DEFAULT_TIME_ZONE),
    },
    unique_key=("provider", "ticker", "date", "action"),
    analysis_date_col="date",
    quality_rules=(
        NoFutureDates(["date"]),
        NoDuplicateRows(["ticker", "date", "action"]),
    ),
)


SHARADAR_DAILY: Final[TableSchema] = TableSchema(
    table="sharadar_daily",
    schema={
        "provider": pl.String,
        "date": pl.Date,
        "ticker": pl.String,
        "marketcap": pl.Float64,
        "ev": pl.Float64,
        "pe": pl.Float64,
        "pb": pl.Float64,
        "ps": pl.Float64,
        "evebit": pl.Float64,
        "evebitda": pl.Float64,
        "lastupdated": pl.Date,
        "fetched_at": pl.Datetime(time_zone=DEFAULT_TIME_ZONE),
    },
    unique_key=("provider", "ticker", "date"),
    analysis_date_col="date",
    quality_rules=(
        NoFutureDates(["date"]),
        NoDuplicateRows(["ticker", "date"]),
    ),
)


SHARADAR_SP500: Final[TableSchema] = TableSchema(
    table="sharadar_sp500",
    schema={
        "provider": pl.String,
        "date": pl.Date,
        "action": pl.String,
        "ticker": pl.String,
        "name": pl.String,
        "contraticker": pl.String,
        "contraname": pl.String,
        "note": pl.String,
        "fetched_at": pl.Datetime(time_zone=DEFAULT_TIME_ZONE),
    },
    unique_key=("provider", "ticker", "date", "action"),
    analysis_date_col="date",
    quality_rules=(
        NoFutureDates(["date"]),
        NoDuplicateRows(["ticker", "date", "action"]),
    ),
)


TABLES: Final[dict[str, TableSchema]] = {
    t.table: t
    for t in [
        SHARADAR_SEP,
        SHARADAR_TICKERS,
        SHARADAR_SF1,
        SHARADAR_SF2,
        SHARADAR_SF3,
        SHARADAR_ACTIONS,
        SHARADAR_DAILY,
        SHARADAR_SP500,
    ]
}

DATASETS: Final[tuple[DatasetSpec, ...]] = (
    DatasetSpec(name="price", schema=SHARADAR_SEP, endpoint="SEP", date_filter_col="date"),
    DatasetSpec(name="tickers", schema=SHARADAR_TICKERS, endpoint="TICKERS"),
    DatasetSpec(name="fundamental", schema=SHARADAR_SF1, endpoint="SF1", date_filter_col="calendardate"),
    DatasetSpec(name="daily", schema=SHARADAR_DAILY, endpoint="DAILY", date_filter_col="date"),
    DatasetSpec(name="actions", schema=SHARADAR_ACTIONS, endpoint="ACTIONS", date_filter_col="date"),
    DatasetSpec(name="insider", schema=SHARADAR_SF2, endpoint="SF2", date_filter_col="filingdate"),
    DatasetSpec(name="institutional", schema=SHARADAR_SF3, endpoint="SF3", date_filter_col="calendardate"),
    DatasetSpec(name="sp500", schema=SHARADAR_SP500, endpoint="SP500", date_filter_col="date"),
)

DATASET_SPECS: Final[dict[str, DatasetSpec]] = {spec.name: spec for spec in DATASETS}
DATASET_NAMES: Final[tuple[str, ...]] = tuple(spec.name for spec in DATASETS)
